GET http://localhost:5124/books

###
GET http://localhost:5124/books/1

### 
POST http://localhost:5124/books
Content-Type: application/json

{
    "name": "pop",
    "genreId": 1
}

###
PUT http://localhost:5124/books/1
Content-Type: application/json

{
    "name": "New Name for the Book",
    "genreId": 3
}

###
DELETE http://localhost:5124/books/1 
